[project]
name = "traj-pred-gpr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jax[cuda12]>=0.6.2",
    "matplotlib>=3.10.8",
    "pyqt6>=6.10.2",
]
